; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_indicator_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
framework = arduino

board = seeed_indicator_rp2040
board_build.core = earlephilhower

extra_scripts = pre:suppress_lib_warnings.py

build_flags =
    -Wno-missing-field-initializers
    -Wno-format
    -Isrc
    -Wl,-Map,.pio/build/output.map
    -Os
    -Wno-unused-variable
    -Wcast-align
    -D__PLAT_RP2040__
    -DHW_SPI1_DEVICE

lib_deps =
    # renovate: datasource=custom.pio depName=Nanopb packageName=nanopb/library/Nanopb
    nanopb/Nanopb@0.4.91

monitor_speed = 115200

debug_tool = cmsis-dap
